#include"test_scp.h"

int main(int argc, char* argv[]){
    vsip_init((void*)0);
    argv++;
    while(--argc >0){
       if(!strcmp(*argv,"cgemp_d")){cgemp_d(); argv++;}
       else if(!strcmp(*argv, "cgemp_d")){ cgemp_d(); argv++; }
       else if(!strcmp(*argv, "cgemp_f")){ cgemp_f(); argv++; }
       else if(!strcmp(*argv, "cgems_d")){ cgems_d(); argv++; }
       else if(!strcmp(*argv, "cgems_f")){ cgems_f(); argv++; }
       else if(!strcmp(*argv, "cmadd_d")){ cmadd_d(); argv++; }
       else if(!strcmp(*argv, "cmadd_f")){ cmadd_f(); argv++; }
       else if(!strcmp(*argv, "cmconj_d")){ cmconj_d(); argv++; }
       else if(!strcmp(*argv, "cmconj_f")){ cmconj_f(); argv++; }
       else if(!strcmp(*argv, "cmdiv_d")){ cmdiv_d(); argv++; }
       else if(!strcmp(*argv, "cmdiv_f")){ cmdiv_f(); argv++; }
       else if(!strcmp(*argv, "cmexp_d")){ cmexp_d(); argv++; }
       else if(!strcmp(*argv, "cmexp_f")){ cmexp_f(); argv++; }
       else if(!strcmp(*argv, "cmexpoavg_d")){ cmexpoavg_d(); argv++; }
       else if(!strcmp(*argv, "cmexpoavg_f")){ cmexpoavg_f(); argv++; }
       else if(!strcmp(*argv, "cmfill_d")){ cmfill_d(); argv++; }
       else if(!strcmp(*argv, "cmfill_f")){ cmfill_f(); argv++; }
       else if(!strcmp(*argv, "cmgather_d")){ cmgather_d(); argv++; }
       else if(!strcmp(*argv, "cmgather_f")){ cmgather_f(); argv++; }
       else if(!strcmp(*argv, "cmherm_d")){ cmherm_d(); argv++; }
       else if(!strcmp(*argv, "cmherm_f")){ cmherm_f(); argv++; }
       else if(!strcmp(*argv, "cmjmul_d")){ cmjmul_d(); argv++; }
       else if(!strcmp(*argv, "cmjmul_f")){ cmjmul_f(); argv++; }
       else if(!strcmp(*argv, "cmlog_d")){ cmlog_d(); argv++; }
       else if(!strcmp(*argv, "cmlog_f")){ cmlog_f(); argv++; }
       else if(!strcmp(*argv, "cmmag_d")){ cmmag_d(); argv++; }
       else if(!strcmp(*argv, "cmmag_f")){ cmmag_f(); argv++; }
       else if(!strcmp(*argv, "cmmeansqval_d")){ cmmeansqval_d(); argv++; }
       else if(!strcmp(*argv, "cmmeansqval_f")){ cmmeansqval_f(); argv++; }
       else if(!strcmp(*argv, "cmmeanval_d")){ cmmeanval_d(); argv++; }
       else if(!strcmp(*argv, "cmmeanval_f")){ cmmeanval_f(); argv++; }
       else if(!strcmp(*argv, "cmmul_d")){ cmmul_d(); argv++; }
       else if(!strcmp(*argv, "cmmul_f")){ cmmul_f(); argv++; }
       else if(!strcmp(*argv, "cmneg_d")){ cmneg_d(); argv++; }
       else if(!strcmp(*argv, "cmneg_f")){ cmneg_f(); argv++; }
       else if(!strcmp(*argv, "cmprod_d")){ cmprod_d(); argv++; }
       else if(!strcmp(*argv, "cmprod_f")){ cmprod_f(); argv++; }
       else if(!strcmp(*argv, "cmprodh_d")){ cmprodh_d(); argv++; }
       else if(!strcmp(*argv, "cmprodh_f")){ cmprodh_f(); argv++; }
       else if(!strcmp(*argv, "cmprodj_d")){ cmprodj_d(); argv++; }
       else if(!strcmp(*argv, "cmprodj_f")){ cmprodj_f(); argv++; }
       else if(!strcmp(*argv, "cmprodt_d")){ cmprodt_d(); argv++; }
       else if(!strcmp(*argv, "cmprodt_f")){ cmprodt_f(); argv++; }
       else if(!strcmp(*argv, "cmrecip_d")){ cmrecip_d(); argv++; }
       else if(!strcmp(*argv, "cmrecip_f")){ cmrecip_f(); argv++; }
       else if(!strcmp(*argv, "cmrsdiv_d")){ cmrsdiv_d(); argv++; }
       else if(!strcmp(*argv, "cmrsdiv_f")){ cmrsdiv_f(); argv++; }
       else if(!strcmp(*argv, "cmscatter_d")){ cmscatter_d(); argv++; }
       else if(!strcmp(*argv, "cmscatter_f")){ cmscatter_f(); argv++; }
       else if(!strcmp(*argv, "cmsqrt_d")){ cmsqrt_d(); argv++; }
       else if(!strcmp(*argv, "cmsqrt_f")){ cmsqrt_f(); argv++; }
       else if(!strcmp(*argv, "cmsub_d")){ cmsub_d(); argv++; }
       else if(!strcmp(*argv, "cmsub_f")){ cmsub_f(); argv++; }
       else if(!strcmp(*argv, "cmswap_d")){ cmswap_d(); argv++; }
       else if(!strcmp(*argv, "cmswap_f")){ cmswap_f(); argv++; }
       else if(!strcmp(*argv, "cmtrans_d")){ cmtrans_d(); argv++; }
       else if(!strcmp(*argv, "cmtrans_f")){ cmtrans_f(); argv++; }
       else if(!strcmp(*argv, "cmvprod_d")){ cmvprod_d(); argv++; }
       else if(!strcmp(*argv, "cmvprod_f")){ cmvprod_f(); argv++; }
       else if(!strcmp(*argv, "crmdiv_d")){ crmdiv_d(); argv++; }
       else if(!strcmp(*argv, "crmdiv_f")){ crmdiv_f(); argv++; }
       else if(!strcmp(*argv, "crmsub_d")){ crmsub_d(); argv++; }
       else if(!strcmp(*argv, "crmsub_f")){ crmsub_f(); argv++; }
       else if(!strcmp(*argv, "crvdiv_d")){ crvdiv_d(); argv++; }
       else if(!strcmp(*argv, "crvdiv_f")){ crvdiv_f(); argv++; }
       else if(!strcmp(*argv, "crvsub_d")){ crvsub_d(); argv++; }
       else if(!strcmp(*argv, "crvsub_f")){ crvsub_f(); argv++; }
       else if(!strcmp(*argv, "csmadd_d")){ csmadd_d(); argv++; }
       else if(!strcmp(*argv, "csmadd_f")){ csmadd_f(); argv++; }
       else if(!strcmp(*argv, "csmdiv_d")){ csmdiv_d(); argv++; }
       else if(!strcmp(*argv, "csmdiv_f")){ csmdiv_f(); argv++; }
       else if(!strcmp(*argv, "csmmul_d")){ csmmul_d(); argv++; }
       else if(!strcmp(*argv, "csmmul_f")){ csmmul_f(); argv++; }
       else if(!strcmp(*argv, "csmsub_d")){ csmsub_d(); argv++; }
       else if(!strcmp(*argv, "csmsub_f")){ csmsub_f(); argv++; }
       else if(!strcmp(*argv, "csvadd_d")){ csvadd_d(); argv++; }
       else if(!strcmp(*argv, "csvadd_f")){ csvadd_f(); argv++; }
       else if(!strcmp(*argv, "csvdiv_d")){ csvdiv_d(); argv++; }
       else if(!strcmp(*argv, "csvdiv_f")){ csvdiv_f(); argv++; }
       else if(!strcmp(*argv, "csvmul_d")){ csvmul_d(); argv++; }
       else if(!strcmp(*argv, "csvmul_f")){ csvmul_f(); argv++; }
       else if(!strcmp(*argv, "cvadd_d")){ cvadd_d(); argv++; }
       else if(!strcmp(*argv, "cvadd_f")){ cvadd_f(); argv++; }
       else if(!strcmp(*argv, "cvam_d")){ cvam_d(); argv++; }
       else if(!strcmp(*argv, "cvam_f")){ cvam_f(); argv++; }
       else if(!strcmp(*argv, "cvconj_d")){ cvconj_d(); argv++; }
       else if(!strcmp(*argv, "cvconj_f")){ cvconj_f(); argv++; }
       else if(!strcmp(*argv, "cvdiv_d")){ cvdiv_d(); argv++; }
       else if(!strcmp(*argv, "cvdiv_f")){ cvdiv_f(); argv++; }
       else if(!strcmp(*argv, "cvdot_d")){ cvdot_d(); argv++; }
       else if(!strcmp(*argv, "cvdot_f")){ cvdot_f(); argv++; }
       else if(!strcmp(*argv, "cvexp_d")){ cvexp_d(); argv++; }
       else if(!strcmp(*argv, "cvexp_f")){ cvexp_f(); argv++; }
       else if(!strcmp(*argv, "cvexpoavg_d")){ cvexpoavg_d(); argv++; }
       else if(!strcmp(*argv, "cvexpoavg_f")){ cvexpoavg_f(); argv++; }
       else if(!strcmp(*argv, "cvfill_d")){ cvfill_d(); argv++; }
       else if(!strcmp(*argv, "cvfill_f")){ cvfill_f(); argv++; }
       else if(!strcmp(*argv, "cvgather_d")){ cvgather_d(); argv++; }
       else if(!strcmp(*argv, "cvgather_f")){ cvgather_f(); argv++; }
       else if(!strcmp(*argv, "cvjdot_d")){ cvjdot_d(); argv++; }
       else if(!strcmp(*argv, "cvjdot_f")){ cvjdot_f(); argv++; }
       else if(!strcmp(*argv, "cvjmul_d")){ cvjmul_d(); argv++; }
       else if(!strcmp(*argv, "cvjmul_f")){ cvjmul_f(); argv++; }
       else if(!strcmp(*argv, "cvlog_d")){ cvlog_d(); argv++; }
       else if(!strcmp(*argv, "cvlog_f")){ cvlog_f(); argv++; }
       else if(!strcmp(*argv, "cvmag_d")){ cvmag_d(); argv++; }
       else if(!strcmp(*argv, "cvmag_f")){ cvmag_f(); argv++; }
       else if(!strcmp(*argv, "cvmeansqval_d")){ cvmeansqval_d(); argv++; }
       else if(!strcmp(*argv, "cvmeansqval_f")){ cvmeansqval_f(); argv++; }
       else if(!strcmp(*argv, "cvmmul_d")){ cvmmul_d(); argv++; }
       else if(!strcmp(*argv, "cvmmul_f")){ cvmmul_f(); argv++; }
       else if(!strcmp(*argv, "cvmprod_d")){ cvmprod_d(); argv++; }
       else if(!strcmp(*argv, "cvmprod_f")){ cvmprod_f(); argv++; }
       else if(!strcmp(*argv, "cvmsa_d")){ cvmsa_d(); argv++; }
       else if(!strcmp(*argv, "cvmsa_f")){ cvmsa_f(); argv++; }
       else if(!strcmp(*argv, "cvmul_d")){ cvmul_d(); argv++; }
       else if(!strcmp(*argv, "cvmul_f")){ cvmul_f(); argv++; }
       else if(!strcmp(*argv, "cvneg_d")){ cvneg_d(); argv++; }
       else if(!strcmp(*argv, "cvneg_f")){ cvneg_f(); argv++; }
       else if(!strcmp(*argv, "cvouter_d")){ cvouter_d(); argv++; }
       else if(!strcmp(*argv, "cvouter_f")){ cvouter_f(); argv++; }
       else if(!strcmp(*argv, "cvrsdiv_d")){ cvrsdiv_d(); argv++; }
       else if(!strcmp(*argv, "cvrsdiv_f")){ cvrsdiv_f(); argv++; }
       else if(!strcmp(*argv, "cvsam_d")){ cvsam_d(); argv++; }
       else if(!strcmp(*argv, "cvsam_f")){ cvsam_f(); argv++; }
       else if(!strcmp(*argv, "cvscatter_d")){ cvscatter_d(); argv++; }
       else if(!strcmp(*argv, "cvscatter_f")){ cvscatter_f(); argv++; }
       else if(!strcmp(*argv, "cvsma_d")){ cvsma_d(); argv++; }
       else if(!strcmp(*argv, "cvsma_f")){ cvsma_f(); argv++; }
       else if(!strcmp(*argv, "cvsub_d")){ cvsub_d(); argv++; }
       else if(!strcmp(*argv, "cvsub_f")){ cvsub_f(); argv++; }
       else if(!strcmp(*argv, "cvswap_d")){ cvswap_d(); argv++; }
       else if(!strcmp(*argv, "cvswap_f")){ cvswap_f(); argv++; }
       else if(!strcmp(*argv, "gemp_d")){ gemp_d(); argv++; }
       else if(!strcmp(*argv, "gemp_f")){ gemp_f(); argv++; }
       else if(!strcmp(*argv, "gems_d")){ gems_d(); argv++; }
       else if(!strcmp(*argv, "gems_f")){ gems_f(); argv++; }
       else if(!strcmp(*argv, "macos_d")){ macos_d(); argv++; }
       else if(!strcmp(*argv, "macos_f")){ macos_f(); argv++; }
       else if(!strcmp(*argv, "madd_d")){ madd_d(); argv++; }
       else if(!strcmp(*argv, "madd_f")){ madd_f(); argv++; }
       else if(!strcmp(*argv, "malltrue_bl")){ malltrue_bl(); argv++; }
       else if(!strcmp(*argv, "manytrue_bl")){ manytrue_bl(); argv++; }
       else if(!strcmp(*argv, "marg_d")){ marg_d(); argv++; }
       else if(!strcmp(*argv, "marg_f")){ marg_f(); argv++; }
       else if(!strcmp(*argv, "masin_d")){ masin_d(); argv++; }
       else if(!strcmp(*argv, "masin_f")){ masin_f(); argv++; }
       else if(!strcmp(*argv, "matan2_d")){ matan2_d(); argv++; }
       else if(!strcmp(*argv, "matan2_f")){ matan2_f(); argv++; }
       else if(!strcmp(*argv, "matan_d")){ matan_d(); argv++; }
       else if(!strcmp(*argv, "matan_f")){ matan_f(); argv++; }
       else if(!strcmp(*argv, "mclip_d")){ mclip_d(); argv++; }
       else if(!strcmp(*argv, "mclip_f")){ mclip_f(); argv++; }
       else if(!strcmp(*argv, "mcmagsq_d")){ mcmagsq_d(); argv++; }
       else if(!strcmp(*argv, "mcmagsq_f")){ mcmagsq_f(); argv++; }
       else if(!strcmp(*argv, "mcmaxmgsq_d")){ mcmaxmgsq_d(); argv++; }
       else if(!strcmp(*argv, "mcmaxmgsq_f")){ mcmaxmgsq_f(); argv++; }
       else if(!strcmp(*argv, "mcmaxmgsqval_d")){ mcmaxmgsqval_d(); argv++; }
       else if(!strcmp(*argv, "mcmaxmgsqval_f")){ mcmaxmgsqval_f(); argv++; }
       else if(!strcmp(*argv, "mcminmgsq_d")){ mcminmgsq_d(); argv++; }
       else if(!strcmp(*argv, "mcminmgsq_f")){ mcminmgsq_f(); argv++; }
       else if(!strcmp(*argv, "mcminmgsqval_d")){ mcminmgsqval_d(); argv++; }
       else if(!strcmp(*argv, "mcminmgsqval_f")){ mcminmgsqval_f(); argv++; }
       else if(!strcmp(*argv, "mcos_d")){ mcos_d(); argv++; }
       else if(!strcmp(*argv, "mcos_f")){ mcos_f(); argv++; }
       else if(!strcmp(*argv, "mcosh_d")){ mcosh_d(); argv++; }
       else if(!strcmp(*argv, "mcosh_f")){ mcosh_f(); argv++; }
       else if(!strcmp(*argv, "mdiv_d")){ mdiv_d(); argv++; }
       else if(!strcmp(*argv, "mdiv_f")){ mdiv_f(); argv++; }
       else if(!strcmp(*argv, "meuler_d")){ meuler_d(); argv++; }
       else if(!strcmp(*argv, "meuler_f")){ meuler_f(); argv++; }
       else if(!strcmp(*argv, "mexp10_d")){ mexp10_d(); argv++; }
       else if(!strcmp(*argv, "mexp10_f")){ mexp10_f(); argv++; }
       else if(!strcmp(*argv, "mexp_d")){ mexp_d(); argv++; }
       else if(!strcmp(*argv, "mexp_f")){ mexp_f(); argv++; }
       else if(!strcmp(*argv, "mexpoavg_d")){ mexpoavg_d(); argv++; }
       else if(!strcmp(*argv, "mexpoavg_f")){ mexpoavg_f(); argv++; }
       else if(!strcmp(*argv, "mfill_d")){ mfill_d(); argv++; }
       else if(!strcmp(*argv, "mfill_f")){ mfill_f(); argv++; }
       else if(!strcmp(*argv, "mgather_d")){ mgather_d(); argv++; }
       else if(!strcmp(*argv, "mgather_f")){ mgather_f(); argv++; }
       else if(!strcmp(*argv, "mhypot_d")){ mhypot_d(); argv++; }
       else if(!strcmp(*argv, "mhypot_f")){ mhypot_f(); argv++; }
       else if(!strcmp(*argv, "minvclip_d")){ minvclip_d(); argv++; }
       else if(!strcmp(*argv, "minvclip_f")){ minvclip_f(); argv++; }
       else if(!strcmp(*argv, "mleq_d")){ mleq_d(); argv++; }
       else if(!strcmp(*argv, "mleq_f")){ mleq_f(); argv++; }
       else if(!strcmp(*argv, "mlge_d")){ mlge_d(); argv++; }
       else if(!strcmp(*argv, "mlge_f")){ mlge_f(); argv++; }
       else if(!strcmp(*argv, "mlgt_d")){ mlgt_d(); argv++; }
       else if(!strcmp(*argv, "mlgt_f")){ mlgt_f(); argv++; }
       else if(!strcmp(*argv, "mlle_d")){ mlle_d(); argv++; }
       else if(!strcmp(*argv, "mlle_f")){ mlle_f(); argv++; }
       else if(!strcmp(*argv, "mllt_d")){ mllt_d(); argv++; }
       else if(!strcmp(*argv, "mllt_f")){ mllt_f(); argv++; }
       else if(!strcmp(*argv, "mlne_d")){ mlne_d(); argv++; }
       else if(!strcmp(*argv, "mlne_f")){ mlne_f(); argv++; }
       else if(!strcmp(*argv, "mlog10_d")){ mlog10_d(); argv++; }
       else if(!strcmp(*argv, "mlog10_f")){ mlog10_f(); argv++; }
       else if(!strcmp(*argv, "mlog_d")){ mlog_d(); argv++; }
       else if(!strcmp(*argv, "mlog_f")){ mlog_f(); argv++; }
       else if(!strcmp(*argv, "mmag_d")){ mmag_d(); argv++; }
       else if(!strcmp(*argv, "mmag_f")){ mmag_f(); argv++; }
       else if(!strcmp(*argv, "mmax_d")){ mmax_d(); argv++; }
       else if(!strcmp(*argv, "mmax_f")){ mmax_f(); argv++; }
       else if(!strcmp(*argv, "mmaxmg_d")){ mmaxmg_d(); argv++; }
       else if(!strcmp(*argv, "mmaxmg_f")){ mmaxmg_f(); argv++; }
       else if(!strcmp(*argv, "mmaxmgval_d")){ mmaxmgval_d(); argv++; }
       else if(!strcmp(*argv, "mmaxmgval_f")){ mmaxmgval_f(); argv++; }
       else if(!strcmp(*argv, "mmaxval_d")){ mmaxval_d(); argv++; }
       else if(!strcmp(*argv, "mmaxval_f")){ mmaxval_f(); argv++; }
       else if(!strcmp(*argv, "mmeansqval_d")){ mmeansqval_d(); argv++; }
       else if(!strcmp(*argv, "mmeansqval_f")){ mmeansqval_f(); argv++; }
       else if(!strcmp(*argv, "mmeanval_d")){ mmeanval_d(); argv++; }
       else if(!strcmp(*argv, "mmeanval_f")){ mmeanval_f(); argv++; }
       else if(!strcmp(*argv, "mmin_d")){ mmin_d(); argv++; }
       else if(!strcmp(*argv, "mmin_f")){ mmin_f(); argv++; }
       else if(!strcmp(*argv, "mminmg_d")){ mminmg_d(); argv++; }
       else if(!strcmp(*argv, "mminmg_f")){ mminmg_f(); argv++; }
       else if(!strcmp(*argv, "mminmgval_d")){ mminmgval_d(); argv++; }
       else if(!strcmp(*argv, "mminmgval_f")){ mminmgval_f(); argv++; }
       else if(!strcmp(*argv, "mminval_d")){ mminval_d(); argv++; }
       else if(!strcmp(*argv, "mminval_f")){ mminval_f(); argv++; }
       else if(!strcmp(*argv, "mmul_d")){ mmul_d(); argv++; }
       else if(!strcmp(*argv, "mmul_f")){ mmul_f(); argv++; }
       else if(!strcmp(*argv, "mneg_d")){ mneg_d(); argv++; }
       else if(!strcmp(*argv, "mneg_f")){ mneg_f(); argv++; }
       else if(!strcmp(*argv, "mprod_d")){ mprod_d(); argv++; }
       else if(!strcmp(*argv, "mprod_f")){ mprod_f(); argv++; }
       else if(!strcmp(*argv, "mprodt_d")){ mprodt_d(); argv++; }
       else if(!strcmp(*argv, "mprodt_f")){ mprodt_f(); argv++; }
       else if(!strcmp(*argv, "mrecip_d")){ mrecip_d(); argv++; }
       else if(!strcmp(*argv, "mrecip_f")){ mrecip_f(); argv++; }
       else if(!strcmp(*argv, "mrsqrt_d")){ mrsqrt_d(); argv++; }
       else if(!strcmp(*argv, "mrsqrt_f")){ mrsqrt_f(); argv++; }
       else if(!strcmp(*argv, "mscatter_d")){ mscatter_d(); argv++; }
       else if(!strcmp(*argv, "mscatter_f")){ mscatter_f(); argv++; }
       else if(!strcmp(*argv, "msdiv_d")){ msdiv_d(); argv++; }
       else if(!strcmp(*argv, "msdiv_f")){ msdiv_f(); argv++; }
       else if(!strcmp(*argv, "msin_d")){ msin_d(); argv++; }
       else if(!strcmp(*argv, "msin_f")){ msin_f(); argv++; }
       else if(!strcmp(*argv, "msinh_d")){ msinh_d(); argv++; }
       else if(!strcmp(*argv, "msinh_f")){ msinh_f(); argv++; }
       else if(!strcmp(*argv, "msq_d")){ msq_d(); argv++; }
       else if(!strcmp(*argv, "msq_f")){ msq_f(); argv++; }
       else if(!strcmp(*argv, "msqrt_d")){ msqrt_d(); argv++; }
       else if(!strcmp(*argv, "msqrt_f")){ msqrt_f(); argv++; }
       else if(!strcmp(*argv, "msub_d")){ msub_d(); argv++; }
       else if(!strcmp(*argv, "msub_f")){ msub_f(); argv++; }
       else if(!strcmp(*argv, "msumsqval_d")){ msumsqval_d(); argv++; }
       else if(!strcmp(*argv, "msumsqval_f")){ msumsqval_f(); argv++; }
       else if(!strcmp(*argv, "msumval_bl")){ msumval_bl(); argv++; }
       else if(!strcmp(*argv, "msumval_d")){ msumval_d(); argv++; }
       else if(!strcmp(*argv, "msumval_f")){ msumval_f(); argv++; }
       else if(!strcmp(*argv, "mswap_d")){ mswap_d(); argv++; }
       else if(!strcmp(*argv, "mswap_f")){ mswap_f(); argv++; }
       else if(!strcmp(*argv, "mtan_d")){ mtan_d(); argv++; }
       else if(!strcmp(*argv, "mtan_f")){ mtan_f(); argv++; }
       else if(!strcmp(*argv, "mtanh_d")){ mtanh_d(); argv++; }
       else if(!strcmp(*argv, "mtanh_f")){ mtanh_f(); argv++; }
       else if(!strcmp(*argv, "mtrans_d")){ mtrans_d(); argv++; }
       else if(!strcmp(*argv, "mtrans_f")){ mtrans_f(); argv++; }
       else if(!strcmp(*argv, "mvprod_d")){ mvprod_d(); argv++; }
       else if(!strcmp(*argv, "mvprod_f")){ mvprod_f(); argv++; }
       else if(!strcmp(*argv, "rcmadd_d")){ rcmadd_d(); argv++; }
       else if(!strcmp(*argv, "rcmadd_f")){ rcmadd_f(); argv++; }
       else if(!strcmp(*argv, "rcmdiv_d")){ rcmdiv_d(); argv++; }
       else if(!strcmp(*argv, "rcmdiv_f")){ rcmdiv_f(); argv++; }
       else if(!strcmp(*argv, "rcmmul_d")){ rcmmul_d(); argv++; }
       else if(!strcmp(*argv, "rcmmul_f")){ rcmmul_f(); argv++; }
       else if(!strcmp(*argv, "rcmsub_d")){ rcmsub_d(); argv++; }
       else if(!strcmp(*argv, "rcmsub_f")){ rcmsub_f(); argv++; }
       else if(!strcmp(*argv, "rcvadd_d")){ rcvadd_d(); argv++; }
       else if(!strcmp(*argv, "rcvadd_f")){ rcvadd_f(); argv++; }
       else if(!strcmp(*argv, "rcvdiv_d")){ rcvdiv_d(); argv++; }
       else if(!strcmp(*argv, "rcvdiv_f")){ rcvdiv_f(); argv++; }
       else if(!strcmp(*argv, "rcvmul_d")){ rcvmul_d(); argv++; }
       else if(!strcmp(*argv, "rcvmul_f")){ rcvmul_f(); argv++; }
       else if(!strcmp(*argv, "rcvsub_d")){ rcvsub_d(); argv++; }
       else if(!strcmp(*argv, "rcvsub_f")){ rcvsub_f(); argv++; }
       else if(!strcmp(*argv, "rscmadd_d")){ rscmadd_d(); argv++; }
       else if(!strcmp(*argv, "rscmadd_f")){ rscmadd_f(); argv++; }
       else if(!strcmp(*argv, "rscmdiv_d")){ rscmdiv_d(); argv++; }
       else if(!strcmp(*argv, "rscmdiv_f")){ rscmdiv_f(); argv++; }
       else if(!strcmp(*argv, "rscmmul_d")){ rscmmul_d(); argv++; }
       else if(!strcmp(*argv, "rscmmul_f")){ rscmmul_f(); argv++; }
       else if(!strcmp(*argv, "rscmsub_d")){ rscmsub_d(); argv++; }
       else if(!strcmp(*argv, "rscmsub_f")){ rscmsub_f(); argv++; }
       else if(!strcmp(*argv, "rscvadd_d")){ rscvadd_d(); argv++; }
       else if(!strcmp(*argv, "rscvadd_f")){ rscvadd_f(); argv++; }
       else if(!strcmp(*argv, "rscvdiv_d")){ rscvdiv_d(); argv++; }
       else if(!strcmp(*argv, "rscvdiv_f")){ rscvdiv_f(); argv++; }
       else if(!strcmp(*argv, "rvcmmul_d")){ rvcmmul_d(); argv++; }
       else if(!strcmp(*argv, "rvcmmul_f")){ rvcmmul_f(); argv++; }
       else if(!strcmp(*argv, "smadd_d")){ smadd_d(); argv++; }
       else if(!strcmp(*argv, "smadd_f")){ smadd_f(); argv++; }
       else if(!strcmp(*argv, "smdiv_d")){ smdiv_d(); argv++; }
       else if(!strcmp(*argv, "smdiv_f")){ smdiv_f(); argv++; }
       else if(!strcmp(*argv, "smmul_d")){ smmul_d(); argv++; }
       else if(!strcmp(*argv, "smmul_f")){ smmul_f(); argv++; }
       else if(!strcmp(*argv, "smsub_d")){ smsub_d(); argv++; }
       else if(!strcmp(*argv, "smsub_f")){ smsub_f(); argv++; }
       else if(!strcmp(*argv, "svadd_d")){ svadd_d(); argv++; }
       else if(!strcmp(*argv, "svadd_f")){ svadd_f(); argv++; }
       else if(!strcmp(*argv, "svmul_d")){ svmul_d(); argv++; }
       else if(!strcmp(*argv, "svmul_f")){ svmul_f(); argv++; }
       else if(!strcmp(*argv, "vacos_d")){ vacos_d(); argv++; }
       else if(!strcmp(*argv, "vacos_f")){ vacos_f(); argv++; }
       else if(!strcmp(*argv, "vadd_d")){ vadd_d(); argv++; }
       else if(!strcmp(*argv, "vadd_f")){ vadd_f(); argv++; }
       else if(!strcmp(*argv, "valltrue_bl")){ valltrue_bl(); argv++; }
       else if(!strcmp(*argv, "vam_d")){ vam_d(); argv++; }
       else if(!strcmp(*argv, "vam_f")){ vam_f(); argv++; }
       else if(!strcmp(*argv, "vanytrue_bl")){ vanytrue_bl(); argv++; }
       else if(!strcmp(*argv, "varg_d")){ varg_d(); argv++; }
       else if(!strcmp(*argv, "varg_f")){ varg_f(); argv++; }
       else if(!strcmp(*argv, "vasin_d")){ vasin_d(); argv++; }
       else if(!strcmp(*argv, "vasin_f")){ vasin_f(); argv++; }
       else if(!strcmp(*argv, "vatan2_d")){ vatan2_d(); argv++; }
       else if(!strcmp(*argv, "vatan2_f")){ vatan2_f(); argv++; }
       else if(!strcmp(*argv, "vatan_d")){ vatan_d(); argv++; }
       else if(!strcmp(*argv, "vatan_f")){ vatan_f(); argv++; }
       else if(!strcmp(*argv, "vclip_d")){ vclip_d(); argv++; }
       else if(!strcmp(*argv, "vclip_f")){ vclip_f(); argv++; }
       else if(!strcmp(*argv, "vcmaxmgsq_d")){ vcmaxmgsq_d(); argv++; }
       else if(!strcmp(*argv, "vcmaxmgsq_f")){ vcmaxmgsq_f(); argv++; }
       else if(!strcmp(*argv, "vcminmgsqval_d")){ vcminmgsqval_d(); argv++; }
       else if(!strcmp(*argv, "vcminmgsqval_f")){ vcminmgsqval_f(); argv++; }
       else if(!strcmp(*argv, "vcmplx_d")){ vcmplx_d(); argv++; }
       else if(!strcmp(*argv, "vcmplx_f")){ vcmplx_f(); argv++; }
       else if(!strcmp(*argv, "vcos_d")){ vcos_d(); argv++; }
       else if(!strcmp(*argv, "vcos_f")){ vcos_f(); argv++; }
       else if(!strcmp(*argv, "vcosh_d")){ vcosh_d(); argv++; }
       else if(!strcmp(*argv, "vcosh_f")){ vcosh_f(); argv++; }
       else if(!strcmp(*argv, "vdiv_d")){ vdiv_d(); argv++; }
       else if(!strcmp(*argv, "vdiv_f")){ vdiv_f(); argv++; }
       else if(!strcmp(*argv, "vdot_d")){ vdot_d(); argv++; }
       else if(!strcmp(*argv, "vdot_f")){ vdot_f(); argv++; }
       else if(!strcmp(*argv, "veuler_d")){ veuler_d(); argv++; }
       else if(!strcmp(*argv, "veuler_f")){ veuler_f(); argv++; }
       else if(!strcmp(*argv, "vexp_d")){ vexp_d(); argv++; }
       else if(!strcmp(*argv, "vexp_f")){ vexp_f(); argv++; }
       else if(!strcmp(*argv, "vexpoavg_d")){ vexpoavg_d(); argv++; }
       else if(!strcmp(*argv, "vexpoavg_f")){ vexpoavg_f(); argv++; }
       else if(!strcmp(*argv, "vfill_d")){ vfill_d(); argv++; }
       else if(!strcmp(*argv, "vfill_f")){ vfill_f(); argv++; }
       else if(!strcmp(*argv, "vgather_d")){ vgather_d(); argv++; }
       else if(!strcmp(*argv, "vgather_f")){ vgather_f(); argv++; }
       else if(!strcmp(*argv, "vhisto_d")){ vhisto_d(); argv++; }
       else if(!strcmp(*argv, "vhisto_f")){ vhisto_f(); argv++; }
       else if(!strcmp(*argv, "vhypot_d")){ vhypot_d(); argv++; }
       else if(!strcmp(*argv, "vhypot_f")){ vhypot_f(); argv++; }
       else if(!strcmp(*argv, "vimag_d")){ vimag_d(); argv++; }
       else if(!strcmp(*argv, "vimag_f")){ vimag_f(); argv++; }
       else if(!strcmp(*argv, "vinvclip_d")){ vinvclip_d(); argv++; }
       else if(!strcmp(*argv, "vinvclip_f")){ vinvclip_f(); argv++; }
       else if(!strcmp(*argv, "vleq_d")){ vleq_d(); argv++; }
       else if(!strcmp(*argv, "vleq_f")){ vleq_f(); argv++; }
       else if(!strcmp(*argv, "vlge_d")){ vlge_d(); argv++; }
       else if(!strcmp(*argv, "vlge_f")){ vlge_f(); argv++; }
       else if(!strcmp(*argv, "vlgt_d")){ vlgt_d(); argv++; }
       else if(!strcmp(*argv, "vlgt_f")){ vlgt_f(); argv++; }
       else if(!strcmp(*argv, "vlle_d")){ vlle_d(); argv++; }
       else if(!strcmp(*argv, "vlle_f")){ vlle_f(); argv++; }
       else if(!strcmp(*argv, "vllt_d")){ vllt_d(); argv++; }
       else if(!strcmp(*argv, "vllt_f")){ vllt_f(); argv++; }
       else if(!strcmp(*argv, "vlne_d")){ vlne_d(); argv++; }
       else if(!strcmp(*argv, "vlne_f")){ vlne_f(); argv++; }
       else if(!strcmp(*argv, "vlog10_d")){ vlog10_d(); argv++; }
       else if(!strcmp(*argv, "vlog10_f")){ vlog10_f(); argv++; }
       else if(!strcmp(*argv, "vlog_d")){ vlog_d(); argv++; }
       else if(!strcmp(*argv, "vlog_f")){ vlog_f(); argv++; }
       else if(!strcmp(*argv, "vmag_d")){ vmag_d(); argv++; }
       else if(!strcmp(*argv, "vmag_f")){ vmag_f(); argv++; }
       else if(!strcmp(*argv, "vmax_d")){ vmax_d(); argv++; }
       else if(!strcmp(*argv, "vmax_f")){ vmax_f(); argv++; }
       else if(!strcmp(*argv, "vmaxmg_d")){ vmaxmg_d(); argv++; }
       else if(!strcmp(*argv, "vmaxmg_f")){ vmaxmg_f(); argv++; }
       else if(!strcmp(*argv, "vmeansqval_d")){ vmeansqval_d(); argv++; }
       else if(!strcmp(*argv, "vmeansqval_f")){ vmeansqval_f(); argv++; }
       else if(!strcmp(*argv, "vmin_d")){ vmin_d(); argv++; }
       else if(!strcmp(*argv, "vmin_f")){ vmin_f(); argv++; }
       else if(!strcmp(*argv, "vminmg_d")){ vminmg_d(); argv++; }
       else if(!strcmp(*argv, "vminmg_f")){ vminmg_f(); argv++; }
       else if(!strcmp(*argv, "vmmul_d")){ vmmul_d(); argv++; }
       else if(!strcmp(*argv, "vmmul_f")){ vmmul_f(); argv++; }
       else if(!strcmp(*argv, "vmodulate_d")){ vmodulate_d(); argv++; }
       else if(!strcmp(*argv, "vmodulate_f")){ vmodulate_f(); argv++; }
       else if(!strcmp(*argv, "vmprod_d")){ vmprod_d(); argv++; }
       else if(!strcmp(*argv, "vmprod_f")){ vmprod_f(); argv++; }
       else if(!strcmp(*argv, "vmsa_d")){ vmsa_d(); argv++; }
       else if(!strcmp(*argv, "vmsa_f")){ vmsa_f(); argv++; }
       else if(!strcmp(*argv, "vmul_d")){ vmul_d(); argv++; }
       else if(!strcmp(*argv, "vmul_f")){ vmul_f(); argv++; }
       else if(!strcmp(*argv, "vneg_d")){ vneg_d(); argv++; }
       else if(!strcmp(*argv, "vneg_f")){ vneg_f(); argv++; }
       else if(!strcmp(*argv, "vnot_bl")){ vnot_bl(); argv++; }
       else if(!strcmp(*argv, "vouter_d")){ vouter_d(); argv++; }
       else if(!strcmp(*argv, "vouter_f")){ vouter_f(); argv++; }
       else if(!strcmp(*argv, "vpolar_d")){ vpolar_d(); argv++; }
       else if(!strcmp(*argv, "vpolar_f")){ vpolar_f(); argv++; }
       else if(!strcmp(*argv, "vramp_d")){ vramp_d(); argv++; }
       else if(!strcmp(*argv, "vramp_f")){ vramp_f(); argv++; }
       else if(!strcmp(*argv, "vreal_d")){ vreal_d(); argv++; }
       else if(!strcmp(*argv, "vreal_f")){ vreal_f(); argv++; }
       else if(!strcmp(*argv, "vrecip_d")){ vrecip_d(); argv++; }
       else if(!strcmp(*argv, "vrecip_f")){ vrecip_f(); argv++; }
       else if(!strcmp(*argv, "vrect_d")){ vrect_d(); argv++; }
       else if(!strcmp(*argv, "vrect_f")){ vrect_f(); argv++; }
       else if(!strcmp(*argv, "vsam_d")){ vsam_d(); argv++; }
       else if(!strcmp(*argv, "vsam_f")){ vsam_f(); argv++; }
       else if(!strcmp(*argv, "vscatter_d")){ vscatter_d(); argv++; }
       else if(!strcmp(*argv, "vscatter_f")){ vscatter_f(); argv++; }
       else if(!strcmp(*argv, "vsdiv_d")){ vsdiv_d(); argv++; }
       else if(!strcmp(*argv, "vsdiv_f")){ vsdiv_f(); argv++; }
       else if(!strcmp(*argv, "vsin_d")){ vsin_d(); argv++; }
       else if(!strcmp(*argv, "vsin_f")){ vsin_f(); argv++; }
       else if(!strcmp(*argv, "vsinh_d")){ vsinh_d(); argv++; }
       else if(!strcmp(*argv, "vsinh_f")){ vsinh_f(); argv++; }
       else if(!strcmp(*argv, "vsma_d")){ vsma_d(); argv++; }
       else if(!strcmp(*argv, "vsma_f")){ vsma_f(); argv++; }
       else if(!strcmp(*argv, "vsub_d")){ vsub_d(); argv++; }
       else if(!strcmp(*argv, "vsub_f")){ vsub_f(); argv++; }
       else if(!strcmp(*argv, "vsumval_bl")){ vsumval_bl(); argv++; }
       else if(!strcmp(*argv, "vsumval_d")){ vsumval_d(); argv++; }
       else if(!strcmp(*argv, "vsumval_f")){ vsumval_f(); argv++; }
       else if(!strcmp(*argv, "vtan_d")){ vtan_d(); argv++; }
       else if(!strcmp(*argv, "vtan_f")){ vtan_f(); argv++; }
       else if(!strcmp(*argv, "vtanh_d")){ vtanh_d(); argv++; }
       else if(!strcmp(*argv, "vtanh_f")){ vtanh_f(); argv++; }
       else if(!strcmp(*argv, "mindexbool")){ mindexbool(); argv++; }
   }
   vsip_finalize((void*)0);
   return 0;
}
